# This compose file is compatible with Compose itself, it might need some
# adjustments to run properly with stack.

version: '3'

services:

  synapse:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    volumes:
      - "./data/matrix/synapse:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.synapse.loadbalancer.server.port=8008"
      - "traefik.http.routers.synapse.rule=Host(`synapse.sosthene.net`)"
      - "traefik.http.routers.synapse.entrypoints=web-secure"
      - "traefik.http.routers.synapse.tls.certresolver=letsencrypt"

  db:
    image: postgres:10
    restart: "unless-stopped"
    volumes:
      - "./data/postgres/data:/var/lib/postgresql/data"
      - "./data/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql"

  traefik:
    image: traefik:latest
    restart: "unless-stopped"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/sosthene/Synapse/data/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "/home/sosthene/Synapse/data/traefik/config:/config:ro"

  redis:
    image: redis:latest
    restart: "unless-stopped"
  
  nginx:
    image: "nginx:latest"
    restart: "unless-stopped"
    volumes:
      - "./data/matrix/nginx/matrix.conf:/etc/nginx/conf.d/matrix.conf"
      - "./data/matrix/nginx/www:/var/www/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.matrix.loadbalancer.server.port=80"
      - "traefik.http.routers.matrix.rule=Host(`matrix.sosthene.net`)"
      - "traefik.http.routers.matrix.entrypoints=web-secure"
      - "traefik.http.routers.matrix.tls.certresolver=letsencrypt"
